SELECT
  SchoolId,
  CONCAT(StateCountyCode, StateDistrictCode, StateSchoolCode) AS StateCdsCode, 
  StateCountyCode,
  StateDistrictCode,
  StateSchoolCode,
  SchoolNameFull,
  SchoolNameMid,
  SchoolNameShort,
  SchoolType,
  GradesServed,
  Grade5,
  Grade6,
  Grade7,
  Grade8,
  Grade9,
  Grade10,
  Grade11,
  Grade12,
  CAST(YearOpened AS INT64) AS YearOpened,
  PreviousRenewalYears,
  DATE(CurrentCharterTermStartDate) AS CurrentCharterTermStartDate,
  DATE(CurrentCharterTermEndDate) AS CurrentCharterTermEndDate
FROM {{ source('RawData', 'Schools')}}