SELECT
  County_Code,
  District_Code,
  School_Code,
  Filler,
  Test_Year,
  Subgroup_ID,
  Test_Type,
  Grade,
  Test_Id,
  Students_Tested,
  CAST(NULLIF(Mean_Scale_Score, '*') AS FLOAT64) AS Mean_Scale_Score,
  CAST(NULLIF(Percentage_Standard_Exceeded, '*') AS FLOAT64) AS Percentage_Standard_Exceeded,
  CAST(NULLIF(Percentage_Standard_Met, '*') AS FLOAT64) AS Percentage_Standard_Met,
  CAST(NULLIF(Percentage_Standard_Met_and_Above, '*') AS FLOAT64) AS Percentage_Standard_Met_and_Above,
  CAST(NULLIF(Percentage_Standard_Nearly_Met, '*') AS FLOAT64) AS Percentage_Standard_Nearly_Met,
  CAST(NULLIF(Percentage_Standard_Not_Met, '*') AS FLOAT64) AS Percentage_Standard_Not_Met,
  Students_with_Scores,
  CAST(NULLIF(Area_1_Percentage_Above_Standard, '*') AS FLOAT64) AS Area_1_Percentage_Above_Standard,
  CAST(NULLIF(Area_1_Percentage_Near_Standard, '*') AS FLOAT64) AS Area_1_Percentage_Near_Standard,
  CAST(NULLIF(Area_1_Percentage_Below_Standard, '*') AS FLOAT64) AS Area_1_Percentage_Below_Standard,
  CAST(NULLIF(Area_2_Percentage_Above_Standard, '*') AS FLOAT64) AS Area_2_Percentage_Above_Standard,
  CAST(NULLIF(Area_2_Percentage_Near_Standard, '*') AS FLOAT64) AS Area_2_Percentage_Near_Standard,
  CAST(NULLIF(Area_2_Percentage_Below_Standard, '*') AS FLOAT64) AS Area_2_Percentage_Below_Standard,
  CAST(NULLIF(Area_3_Percentage_Above_Standard, '*') AS FLOAT64) AS Area_3_Percentage_Above_Standard,
  CAST(NULLIF(Area_3_Percentage_Near_Standard, '*') AS FLOAT64) AS Area_3_Percentage_Near_Standard,
  CAST(NULLIF(Area_3_Percentage_Below_Standard, '*') AS FLOAT64) AS Area_3_Percentage_Below_Standard,
  CAST(NULLIF(Area_4_Percentage_Above_Standard, '*') AS FLOAT64) AS Area_4_Percentage_Above_Standard,
  CAST(NULLIF(Area_4_Percentage_Near_Standard, '*') AS FLOAT64) AS Area_4_Percentage_Near_Standard,
  CAST(NULLIF(Area_4_Percentage_Below_Standard, '*') AS FLOAT64) AS Area_4_Percentage_Below_Standard,
  CAST(NULL AS STRING) AS TypeId,
  Total_Tested_At_Entity_Level AS Total_Tested_At_Reporting_Level,
  Total_Tested_with_Scores AS Total_Tested_with_Scores_at_Reporting_Level,
  CAASPP_Reported_Enrollment AS Students_Enrolled
FROM {{ source('RawData', 'CaasppSantaClaraCounty2016')}}