SELECT
  FORMAT("%02d", County_Code) AS CountyCode,
  FORMAT("%05d", District_Code) AS DistrictCode,
  FORMAT("%07d", School_Code) AS SchoolCode,
  Filler,
  CAST(Test_Year AS INT64) AS TestYear,
  CAST(Subgroup_ID AS STRING) AS DemographicId,
  Test_Type AS TestType,
  CAST(Total_Tested_At_Entity_Level AS INT64) AS TotalTestedAtReportingLevel,
  CAST(NULL AS INT64) AS TotalTestedWithScoresAtReportingLevel,
  CAST(Grade AS INT64) GradeLevel,
  CAST(Test_Id AS STRING) AS TestId,
  CAST(CAASPP_Reported_Enrollment AS INT64) AS StudentsEnrolled,
  CAST(Students_Tested AS INT64) AS StudentsTested,
  CAST(CASE WHEN Mean_Scale_Score NOT IN ('*','','0.0') THEN Mean_Scale_Score END AS FLOAT64) AS MeanScaleScore,
  ROUND(CAST(NULLIF(Percentage_Standard_Exceeded, '*') AS FLOAT64)/100, 4) AS PctStandardExceeded,
  ROUND(CAST(NULLIF(Percentage_Standard_Met, '*') AS FLOAT64)/100, 4) AS PctStandardMet,
  ROUND(CAST(NULLIF(Percentage_Standard_Met_and_Above, '*') AS FLOAT64)/100, 4) AS PctStandardMetandAbove,
  ROUND(CAST(NULLIF(Percentage_Standard_Nearly_Met, '*') AS FLOAT64)/100, 4) AS PctStandardNearlyMet,
  ROUND(CAST(NULLIF(Percentage_Standard_Not_Met, '*') AS FLOAT64)/100, 4) AS PctStandardNotMet,
  CAST(Students_with_Scores AS INT64) AS StudentsWithScores,
  ROUND(CAST(NULLIF(Area_1_Percentage_Above_Standard, '*') AS FLOAT64)/100, 4) AS Area1PctAboveStandard,
  ROUND(CAST(NULLIF(Area_1_Percentage_At_Or_Near_Standard, '*') AS FLOAT64)/100, 4) AS Area1PctNearStandard,
  ROUND(CAST(NULLIF(Area_1_Percentage_Below_Standard, '*') AS FLOAT64)/100, 4) AS Area1PctBelowStandard,
  ROUND(CAST(NULLIF(Area_2_Percentage_Above_Standard, '*') AS FLOAT64)/100, 4) AS Area2PctAboveStandard,
  ROUND(CAST(NULLIF(Area_2_Percentage_At_Or_Near_Standard, '*') AS FLOAT64)/100, 4) AS Area2PctNearStandard,
  ROUND(CAST(NULLIF(Area_2_Percentage_Below_Standard, '*') AS FLOAT64)/100, 4) AS Area2PctBelowStandard,
  ROUND(CAST(NULLIF(Area_3_Percentage_Above_Standard, '*') AS FLOAT64)/100, 4) AS Area3PctAboveStandard,
  ROUND(CAST(NULLIF(Area_3_Percentage_At_Or_Near_Standard, '*') AS FLOAT64)/100, 4) AS Area3PctNearStandard,
  ROUND(CAST(NULLIF(Area_3_Percentage_Below_Standard, '*') AS FLOAT64)/100, 4) AS Area3PctBelowStandard,
  ROUND(CAST(NULLIF(Area_4_Percentage_Above_Standard, '*') AS FLOAT64)/100, 4) AS Area4PctAboveStandard,
  ROUND(CAST(NULLIF(Area_4_Percentage_At_Or_Near_Standard, '*') AS FLOAT64)/100, 4) AS Area4PctNearStandard,
  ROUND(CAST(NULLIF(Area_4_Percentage_Below_Standard, '*') AS FLOAT64)/100, 4) AS Area4PctBelowStandard,
  CAST(NULL AS STRING) AS TypeId
FROM {{ source('RawData', 'Caaspp2015')}}
