select
    academicyear,
    aggregatelevel,
    countycode,
    districtcode,
    schoolcode,
    countyname,
    districtname,
    schoolname,
    charterschool,
    dass,
    reportingcategory,
    cast(nullif(cohortstudents, '*') as int64) as cohortstudents,
    cast(nullif(regular_hs_diploma_graduates__count_, '*') as int64) as regular_hs_diploma_graduates__count_,
    cast(nullif(regular_hs_diploma_graduates__rate_, '*') as float64) as regular_hs_diploma_graduates__rate_,
    cast(nullif(met_uc_csu_grad_req_s__count_, '*') as int64) as met_uc_csu_grad_req_s__count_,
    cast(nullif(met_uc_csu_grad_req_s__rate_, '*') as float64) as met_uc_csu_grad_req_s__rate_,
    cast(nullif(seal_of_biliteracy__count_, '*') as int64) as seal_of_biliteracy__count_,
    cast(nullif(seal_of_biliteracy__rate_, '*') as float64) as seal_of_biliteracy__rate_,
    cast(nullif(golden_state_seal_merit_diploma__count_, '*') as int64) as golden_state_seal_merit_diploma__count_,
    cast(nullif(golden_state_seal_merit_diploma__rate, '*') as float64) as golden_state_seal_merit_diploma__rate,
    cast(nullif(chspe_completer__count_, '*') as int64) as chspe_completer__count_,
    cast(nullif(chspe_completer__rate_, '*') as float64) as chspe_completer__rate_,
    cast(nullif(adult_ed__hs_diploma__count_, '*') as int64) as adult_ed__hs_diploma__count_,
    cast(nullif(adult_ed__hs_diploma__rate_, '*') as float64) as adult_ed__hs_diploma__rate_,
    cast(nullif(sped_certificate__count_, '*') as int64) as sped_certificate__count_,
    cast(nullif(sped_certificate__rate_, '*') as float64) as sped_certificate__rate_,
    cast(nullif(ged_completer__count_, '*') as int64) as ged_completer__count_,
    cast(nullif(ged_completer__rate_, '*') as float64) as ged_completer__rate_,
    cast(nullif(other_transfer__count_, '*') as int64) as other_transfer__count_,
    cast(nullif(other_transfer__rate_, '*') as float64) as other_transfer__rate_,
    cast(nullif(dropout__count_, '*') as int64) as dropout__count_,
    cast(nullif(dropout__rate_, '*') as float64) as dropout__rate_,
    cast(nullif(still_enrolled__count_, '*') as int64) as still_enrolled__count_,
    cast(nullif(still_enrolled__rate_, '*') as float64) as still_enrolled__rate_
from {{ source("RawData", "CdeAdjustedCohortOutcomes2022") }}
