select
    format("%02d", CountyCode) as CountyCode,
    format("%05d", DistrictCode) as DistrictCode,
    format("%07d", SchoolCode) as SchoolCode,
    format("%02d", RecordType) as RecordType,
    cast(CharterNumber as string) as CharterNumber,
    cast(TestYear as int64) as TestYear,
    cast(StudentGroupID as string) as StudentGroupId,
    cast(AssessmentType as string) as AssessmentType,
    cast(nullif(TotalEnrolled, '*') as int64) as TotalEnrolled,
    cast(nullif(TotalTested, '*') as int64) as TotalTested,
    cast(nullif(TotalTestedWithScores, '*') as int64) as TotalTestedWithScores,
    case when Grade = 'KN' then 0 else cast(Grade as int64) end GradeLevel,
    cast(nullif(OverallMeanSclScr, '*') as float64) as OverallMeanSclScr,
    round(cast(nullif(OverallPerfLvl1Pcnt, '*') as float64) / 100, 4) as OverallPerfLvl1Pcnt,
    cast(nullif(OverallPerfLvl1Count, '*') as int64) as OverallPerfLvl1Count,
    round(cast(nullif(OverallPerfLvl2Pcnt, '*') as float64) / 100, 4) as OverallPerfLvl2Pcnt,
    cast(nullif(OverallPerfLvl2Count, '*') as int64) as OverallPerfLvl2Count,
    round(cast(nullif(OverallPerfLvl3Pcnt, '*') as float64) / 100, 4) as OverallPerfLvl3Pcnt,
    cast(nullif(OverallPerfLvl3Count, '*') as int64) as OverallPerfLvl3Count,
    round(cast(nullif(OverallPerfLvl4Pcnt, '*') as float64) / 100, 4) as OverallPerfLvl4Pcnt,
    cast(nullif(OverallPerfLvl4Count, '*') as int64) as OverallPerfLvl4Count,
    cast(nullif(OverallTotal, '*') as int64) as OverallTotal,
    cast(nullif(OralLangMeanSclScr, '*') as float64) as OralLangMeanSclScr,
    round(cast(nullif(OralLangPerfLvl1Pcnt, '*') as float64) / 100, 4) as OralLangPerfLvl1Pcnt,
    cast(nullif(OralLangPerfLvl1Count, '*') as int64) as OralLangPerfLvl1Count,
    round(cast(nullif(OralLangPerfLvl2Pcnt, '*') as float64) / 100, 4) as OralLangPerfLvl2Pcnt,
    cast(nullif(OralLangPerfLvl2Count, '*') as int64) as OralLangPerfLvl2Count,
    round(cast(nullif(OralLangPerfLvl3Pcnt, '*') as float64) / 100, 4) as OralLangPerfLvl3Pcnt,
    cast(nullif(OralLangPerfLvl3Count, '*') as int64) as OralLangPerfLvl3Count,
    round(cast(nullif(OralLangPerfLvl4Pcnt, '*') as float64) / 100, 4) as OralLangPerfLvl4Pcnt,
    cast(nullif(OralLangPerfLvl4Count, '*') as int64) as OralLangPerfLvl4Count,
    cast(nullif(OralLangTotal, '*') as int64) as OralLangTotal,
    cast(nullif(WritLangMeanSclScr, '*') as float64) as WritLangMeanSclScr,
    round(cast(nullif(WritLangPerfLvl1Pcnt, '*') as float64) / 100, 4) as WritLangPerfLvl1Pcnt,
    cast(nullif(WritLangPerfLvl1Count, '*') as int64) as WritLangPerfLvl1Count,
    round(cast(nullif(WritLangPerfLvl2Pcnt, '*') as float64) / 100, 4) as WritLangPerfLvl2Pcnt,
    cast(nullif(WritLangPerfLvl2Count, '*') as int64) as WritLangPerfLvl2Count,
    round(cast(nullif(WritLangPerfLvl3Pcnt, '*') as float64) / 100, 4) as WritLangPerfLvl3Pcnt,
    cast(nullif(WritLangPerfLvl3Count, '*') as int64) as WritLangPerfLvl3Count,
    round(cast(nullif(WritLangPerfLvl4Pcnt, '*') as float64) / 100, 4) as WritLangPerfLvl4Pcnt,
    cast(nullif(WritLangPerfLvl4Count, '*') as int64) as WritLangPerfLvl4Count,
    cast(nullif(WritLangTotal, '*') as int64) as WritLangTotal,
    round(cast(nullif(ListeningDomainBeginPcnt, '*') as float64) / 100, 4) as ListeningDomainBeginPcnt,
    cast(nullif(ListeningDomainBeginCount, '*') as int64) as ListeningDomainBeginCount,
    round(cast(nullif(ListeningDomainModeratePcnt, '*') as float64) / 100, 4) as ListeningDomainModeratePcnt,
    cast(nullif(ListeningDomainModerateCount, '*') as int64) as ListeningDomainModerateCount,
    round(cast(nullif(ListeningDomainDevelopedPcnt, '*') as float64) / 100, 4) as ListeningDomainDevelopedPcnt,
    cast(nullif(ListeningDomainDevelopedCount, '*') as int64) as ListeningDomainDevelopedCount,
    cast(nullif(ListeningDomainTotal, '*') as int64) as ListeningDomainTotal,
    round(cast(nullif(SpeakingDomainBeginPcnt, '*') as float64) / 100, 4) as SpeakingDomainBeginPcnt,
    cast(nullif(SpeakingDomainBeginCount, '*') as int64) as SpeakingDomainBeginCount,
    round(cast(nullif(SpeakingDomainModeratePcnt, '*') as float64) / 100, 4) as SpeakingDomainModeratePcnt,
    cast(nullif(SpeakingDomainModerateCount, '*') as int64) as SpeakingDomainModerateCount,
    round(cast(nullif(SpeakingDomainDevelopedPcnt, '*') as float64) / 100, 4) as SpeakingDomainDevelopedPcnt,
    cast(nullif(SpeakingDomainDevelopedCount, '*') as int64) as SpeakingDomainDevelopedCount,
    cast(nullif(SpeakingDomainTotal, '*') as int64) as SpeakingDomainTotal,
    round(cast(nullif(ReadingDomainBeginPcnt, '*') as float64) / 100, 4) as ReadingDomainBeginPcnt,
    cast(nullif(ReadingDomainBeginCount, '*') as int64) as ReadingDomainBeginCount,
    round(cast(nullif(ReadingDomainModeratePcnt, '*') as float64) / 100, 4) as ReadingDomainModeratePcnt,
    cast(nullif(ReadingDomainModerateCount, '*') as int64) as ReadingDomainModerateCount,
    round(cast(nullif(ReadingDomainDevelopedPcnt, '*') as float64) / 100, 4) as ReadingDomainDevelopedPcnt,
    cast(nullif(ReadingDomainDevelopedCount, '*') as int64) as ReadingDomainDevelopedCount,
    cast(nullif(ReadingDomainTotal, '*') as int64) as ReadingDomainTotal,
    round(cast(nullif(WritingDomainBeginPcnt, '*') as float64) / 100, 4) as WritingDomainBeginPcnt,
    cast(nullif(WritingDomainBeginCount, '*') as int64) as WritingDomainBeginCount,
    round(cast(nullif(WritingDomainModeratePcnt, '*') as float64) / 100, 4) as WritingDomainModeratePcnt,
    cast(nullif(WritingDomainModerateCount, '*') as int64) as WritingDomainModerateCount,
    round(cast(nullif(WritingDomainDevelopedPcnt, '*') as float64) / 100, 4) as WritingDomainDevelopedPcnt,
    cast(nullif(WritingDomainDevelopedCount, '*') as int64) as WritingDomainDevelopedCount,
    cast(nullif(WritingDomainTotal, '*') as int64) as WritingDomainTotal
from {{ source('RawData', 'Elpac2021')}}
