SELECT
    FORMAT("%02d", CountyCode) AS CountyCode,
    FORMAT("%05d", DistrictCode) AS DistrictCode,
    FORMAT("%07d", SchoolCode) AS SchoolCode,
    FORMAT("%02d", RecordType) AS RecordType,
    CAST(CharterNumber AS STRING) AS CharterNumber,
    CAST(TestYear AS INT64) AS TestYear,
    CAST(StudentGroupID AS STRING) AS StudentGroupId,
    CAST(CASE WHEN AssessmentType = 2 THEN 21 END AS STRING) AS AssessmentType,
    CAST(NULLIF(TotalEnrolled, '*') AS INT64) AS TotalEnrolled,
    CAST(CASE WHEN TotalTested NOT IN ('*','') THEN TotalTested END AS INT64) AS TotalTested,
    CAST(NULL AS INT64) AS TotalTestedWithScores,
    CASE WHEN Grade = 'KN' THEN 0 ELSE CAST(Grade AS INT64) END GradeLevel,
    CAST(CASE WHEN OverallMeanSclScr NOT IN ('*','') THEN OverallMeanSclScr END AS FLOAT64) AS OverallMeanSclScr,
    ROUND(CAST(CASE WHEN OverallPerfLvl1Pcnt NOT IN ('*','') THEN OverallPerfLvl1Pcnt END AS FLOAT64)/100, 4) AS OverallPerfLvl1Pcnt,
    CAST(CASE WHEN OverallPerfLvl1Count NOT IN ('*','') THEN OverallPerfLvl1Count END AS INT64) AS OverallPerfLvl1Count,
    ROUND(CAST(CASE WHEN OverallPerfLvl2Pcnt NOT IN ('*','') THEN OverallPerfLvl2Pcnt END AS FLOAT64)/100, 4) AS OverallPerfLvl2Pcnt,
    CAST(CASE WHEN OverallPerfLvl2Count NOT IN ('*','') THEN OverallPerfLvl2Count END AS INT64) AS OverallPerfLvl2Count,
    ROUND(CAST(CASE WHEN OverallPerfLvl3Pcnt NOT IN ('*','') THEN OverallPerfLvl3Pcnt END AS FLOAT64)/100, 4) AS OverallPerfLvl3Pcnt,
    CAST(CASE WHEN OverallPerfLvl3Count NOT IN ('*','') THEN OverallPerfLvl3Count END AS INT64) AS OverallPerfLvl3Count,
    ROUND(CAST(CASE WHEN OverallPerfLvl4Pcnt NOT IN ('*','') THEN OverallPerfLvl4Pcnt END AS FLOAT64)/100, 4) AS OverallPerfLvl4Pcnt,
    CAST(CASE WHEN OverallPerfLvl4Count NOT IN ('*','') THEN OverallPerfLvl4Count END AS INT64) AS OverallPerfLvl4Count,
    CAST(CASE WHEN OverallTotal NOT IN ('*','') THEN OverallTotal END AS INT64) AS OverallTotal,
    CAST(CASE WHEN OralLangMeanSclScr NOT IN ('*','') THEN OralLangMeanSclScr END AS FLOAT64) AS OralLangMeanSclScr,
    ROUND(CAST(CASE WHEN OralLangPerfLvl1Pcnt NOT IN ('*','') THEN OralLangPerfLvl1Pcnt END AS FLOAT64)/100, 4) AS OralLangPerfLvl1Pcnt,
    CAST(CASE WHEN OralLangPerfLvl1Count NOT IN ('*','') THEN OralLangPerfLvl1Count END AS INT64) AS OralLangPerfLvl1Count,
    ROUND(CAST(CASE WHEN OralLangPerfLvl2Pcnt NOT IN ('*','') THEN OralLangPerfLvl2Pcnt END AS FLOAT64)/100, 4) AS OralLangPerfLvl2Pcnt,
    CAST(CASE WHEN OralLangPerfLvl2Count NOT IN ('*','') THEN OralLangPerfLvl2Count END AS INT64) AS OralLangPerfLvl2Count,
    ROUND(CAST(CASE WHEN OralLangPerfLvl3Pcnt NOT IN ('*','') THEN OralLangPerfLvl3Pcnt END AS FLOAT64)/100, 4) AS OralLangPerfLvl3Pcnt,
    CAST(CASE WHEN OralLangPerfLvl3Count NOT IN ('*','') THEN OralLangPerfLvl3Count END AS INT64) AS OralLangPerfLvl3Count,
    ROUND(CAST(CASE WHEN OralLangPerfLvl4Pcnt NOT IN ('*','') THEN OralLangPerfLvl4Pcnt END AS FLOAT64)/100, 4) AS OralLangPerfLvl4Pcnt,
    CAST(CASE WHEN OralLangPerfLvl4Count NOT IN ('*','') THEN OralLangPerfLvl4Count END AS INT64) AS OralLangPerfLvl4Count,
    CAST(CASE WHEN OralLangTotal NOT IN ('*','') THEN OralLangTotal END AS INT64) AS OralLangTotal,
    CAST(CASE WHEN WritLangMeanSclScr NOT IN ('*','') THEN WritLangMeanSclScr END AS FLOAT64) AS WritLangMeanSclScr,
    ROUND(CAST(CASE WHEN WritLangPerfLvl1Pcnt NOT IN ('*','') THEN WritLangPerfLvl1Pcnt END AS FLOAT64)/100, 4) AS WritLangPerfLvl1Pcnt,
    CAST(CASE WHEN WritLangPerfLvl1Count NOT IN ('*','') THEN WritLangPerfLvl1Count END AS INT64) AS WritLangPerfLvl1Count,
    ROUND(CAST(CASE WHEN WritLangPerfLvl2Pcnt NOT IN ('*','') THEN WritLangPerfLvl2Pcnt END AS FLOAT64)/100, 4) AS WritLangPerfLvl2Pcnt,
    CAST(CASE WHEN WritLangPerfLvl2Count NOT IN ('*','') THEN WritLangPerfLvl2Count END AS INT64) AS WritLangPerfLvl2Count,
    ROUND(CAST(CASE WHEN WritLangPerfLvl3Pcnt NOT IN ('*','') THEN WritLangPerfLvl3Pcnt END AS FLOAT64)/100, 4) AS WritLangPerfLvl3Pcnt,
    CAST(CASE WHEN WritLangPerfLvl3Count NOT IN ('*','') THEN WritLangPerfLvl3Count END AS INT64) AS WritLangPerfLvl3Count,
    ROUND(CAST(CASE WHEN WritLangPerfLvl4Pcnt NOT IN ('*','') THEN WritLangPerfLvl4Pcnt END AS FLOAT64)/100, 4) AS WritLangPerfLvl4Pcnt,
    CAST(CASE WHEN WritLangPerfLvl4Count NOT IN ('*','') THEN WritLangPerfLvl4Count END AS INT64) AS WritLangPerfLvl4Count,
    CAST(CASE WHEN WritLangTotal NOT IN ('*','') THEN WritLangTotal END AS INT64) AS WritLangTotal,
    ROUND(CAST(CASE WHEN ListeningDomainBeginPcnt NOT IN ('*','') THEN ListeningDomainBeginPcnt END AS FLOAT64)/100, 4) AS ListeningDomainBeginPcnt,
    CAST(CASE WHEN ListeningDomainBeginCount NOT IN ('*','') THEN ListeningDomainBeginCount END AS INT64) AS ListeningDomainBeginCount,
    ROUND(CAST(CASE WHEN ListeningDomainModeratePcnt NOT IN ('*','') THEN ListeningDomainModeratePcnt END AS FLOAT64)/100, 4) AS ListeningDomainModeratePcnt,
    CAST(CASE WHEN ListeningDomainModerateCount NOT IN ('*','') THEN ListeningDomainModerateCount END AS INT64) AS ListeningDomainModerateCount,
    ROUND(CAST(CASE WHEN ListeningDomainDevelopedPcnt NOT IN ('*','') THEN ListeningDomainDevelopedPcnt END AS FLOAT64)/100, 4) AS ListeningDomainDevelopedPcnt,
    CAST(CASE WHEN ListeningDomainDevelopedCount NOT IN ('*','') THEN ListeningDomainDevelopedCount END AS INT64) AS ListeningDomainDevelopedCount,
    CAST(CASE WHEN ListeningDomainTotal NOT IN ('*','') THEN ListeningDomainTotal END AS INT64) AS ListeningDomainTotal,
    ROUND(CAST(CASE WHEN SpeakingDomainBeginPcnt NOT IN ('*','') THEN SpeakingDomainBeginPcnt END AS FLOAT64)/100, 4) AS SpeakingDomainBeginPcnt,
    CAST(CASE WHEN SpeakingDomainBeginCount NOT IN ('*','') THEN SpeakingDomainBeginCount END AS INT64) AS SpeakingDomainBeginCount,
    ROUND(CAST(CASE WHEN SpeakingDomainModeratePcnt NOT IN ('*','') THEN SpeakingDomainModeratePcnt END AS FLOAT64)/100, 4) AS SpeakingDomainModeratePcnt,
    CAST(CASE WHEN SpeakingDomainModerateCount NOT IN ('*','') THEN SpeakingDomainModerateCount END AS INT64) AS SpeakingDomainModerateCount,
    ROUND(CAST(CASE WHEN SpeakingDomainDevelopedPcnt NOT IN ('*','') THEN SpeakingDomainDevelopedPcnt END AS FLOAT64)/100, 4) AS SpeakingDomainDevelopedPcnt,
    CAST(CASE WHEN SpeakingDomainDevelopedCount NOT IN ('*','') THEN SpeakingDomainDevelopedCount END AS INT64) AS SpeakingDomainDevelopedCount,
    CAST(CASE WHEN SpeakingDomainTotal NOT IN ('*','') THEN SpeakingDomainTotal END AS INT64) AS SpeakingDomainTotal,
    ROUND(CAST(CASE WHEN ReadingDomainBeginPcnt NOT IN ('*','') THEN ReadingDomainBeginPcnt END AS FLOAT64)/100, 4) AS ReadingDomainBeginPcnt,
    CAST(CASE WHEN ReadingDomainBeginCount NOT IN ('*','') THEN ReadingDomainBeginCount END AS INT64) AS ReadingDomainBeginCount,
    ROUND(CAST(CASE WHEN ReadingDomainModeratePcnt NOT IN ('*','') THEN ReadingDomainModeratePcnt END AS FLOAT64)/100, 4) AS ReadingDomainModeratePcnt,
    CAST(CASE WHEN ReadingDomainModerateCount NOT IN ('*','') THEN ReadingDomainModerateCount END AS INT64) AS ReadingDomainModerateCount,
    ROUND(CAST(CASE WHEN ReadingDomainDevelopedPcnt NOT IN ('*','') THEN ReadingDomainDevelopedPcnt END AS FLOAT64)/100, 4) AS ReadingDomainDevelopedPcnt,
    CAST(CASE WHEN ReadingDomainDevelopedCount NOT IN ('*','') THEN ReadingDomainDevelopedCount END AS INT64) AS ReadingDomainDevelopedCount,
    CAST(CASE WHEN ReadingDomainTotal NOT IN ('*','') THEN ReadingDomainTotal END AS INT64) AS ReadingDomainTotal,
    ROUND(CAST(CASE WHEN WritingDomainBeginPcnt NOT IN ('*','') THEN WritingDomainBeginPcnt END AS FLOAT64)/100, 4) AS WritingDomainBeginPcnt,
    CAST(CASE WHEN WritingDomainBeginCount NOT IN ('*','') THEN WritingDomainBeginCount END AS INT64) AS WritingDomainBeginCount,
    ROUND(CAST(CASE WHEN WritingDomainModeratePcnt NOT IN ('*','') THEN WritingDomainModeratePcnt END AS FLOAT64)/100, 4) AS WritingDomainModeratePcnt,
    CAST(CASE WHEN WritingDomainModerateCount NOT IN ('*','') THEN WritingDomainModerateCount END AS INT64) AS WritingDomainModerateCount,
    ROUND(CAST(CASE WHEN WritingDomainDevelopedPcnt NOT IN ('*','') THEN WritingDomainDevelopedPcnt END AS FLOAT64)/100, 4) AS WritingDomainDevelopedPcnt,
    CAST(CASE WHEN WritingDomainDevelopedCount NOT IN ('*','') THEN WritingDomainDevelopedCount END AS INT64) AS WritingDomainDevelopedCount,
    CAST(CASE WHEN WritingDomainTotal NOT IN ('*','') THEN WritingDomainTotal END AS INT64) AS WritingDomainTotal,
FROM {{ source('RawData', 'Elpac2018')}}
