select
    case Subject
        when 'ELA' then '14'
        when 'Math' then '19'
    end as AceAssessmentId,
    concat('ANet ', Subject) as AceAssessmentName,
    case when School_Id = 100966 then '0125617' end as StateSchoolCode,
    cast(School_Year as int64) as School_Year,
    cast(School_Id as int64) as School_Id,
    cast(School_Name as string) as School_Name,
    cast(School_System_Name as string) as School_System_Name,
    cast(School_Cluster as string) as School_Cluster,
    cast(Student_Id as int64) as Student_Id,
    cast(Sas_Id as int64) as Sas_Id,
    cast(Sis_Id as int64) as Sis_Id,
    cast(Student_First_Name as string) as Student_First_Name,
    cast(Student_Middle_Name as string) as Student_Middle_Name,
    cast(Student_Last_Name as string) as Student_Last_Name,
    cast(Enrollment_Grade as string) as Enrollment_Grade,
    cast(Course as string) as Course,
    date(Birth_Date) as Birth_Date,
    cast(Gender as string) as Gender,
    cast(Race as string) as Race,
    cast(Frl_Status as int64) as Frl_Status,
    cast(Lep_Status as int64) as Lep_Status,
    cast(Sped_Status as int64) as Sped_Status,
    cast(Previous_State_Level as string) as Previous_State_Level,
    cast(Previous_State_Score as int64) as Previous_State_Score,
    cast(Period as string) as Period,
    cast(Teacher_First_Name as string) as Teacher_First_Name,
    cast(Teacher_Last_Name as string) as Teacher_Last_Name,
    cast(Cycle as int64) as Cycle,
    cast(Subject as string) as Subject,
    cast(Sas_Name as string) as Sas_Name,
    cast(Assessment_Id as string) as Assessment_Id,
    cast(Assessment_Name as string) as Assessment_Name,
    cast(Super_Genre as string) as Super_Genre,
    cast(Genre as string) as Genre,
    cast(Passage_Id as string) as Passage_Id,
    cast(Passage_Title as string) as Passage_Title,
    cast(Domain as string) as Domain,
    cast(Cluster_Designation as string) as Cluster_Designation,
    cast(Cluster_Code as string) as Cluster_Code,
    cast(Cc_Standard_Code as string) as Cc_Standard_Code,
    cast(Item_Id as string) as Item_Id,
    cast(Question_Id as string) as Question_Id,
    cast(Item_Type as string) as Item_Type,
    cast(Question_Position as string) as Question_Position,
    cast(Response as string) as Response,
    cast(Correct_Answer_Value as string) as Correct_Answer_Value,
    cast(Points_Received as int64) as Points_Received,
    cast(Points_Possible as int64) as Points_Possible,
    case when Item_Type = 'Open Response' then 'Teacher' else 'Machine' end as Scored_By
from {{ source('RawData', 'Anet2022MachineScored') }}
