select
    cast(RecordType as string) as RecordType,
    cast(SSID as string) as SSID,
    StudentLastName,
    StudentFirstName,
    StudentMiddleName,
    date(DateofBirth) as DateofBirth,
    Gender,
    cast(GradeAssessed as string) as GradeAssessed,
    cast(cast(right(cast(CALPADSSchoolCode as string), 7) as int64) as string)
        as CALPADSSchoolCode,
    CALPADSSchoolName,
    cast(Section504Status as bool) as Section504Status,
    cast(CALPADSSpecialEducation as bool) as CALPADSSpecialEducation,
    cast(SpecialEducationforTesting as bool) as SpecialEducationForTesting,
    PrimaryDisabilityType,
    PrimaryDisabilityforTesting,
    cast(MigrantStatus as bool) as MigrantStatus,
    date(ELEntryDate) as ELEntryDate,
    date(ELExitDate) as ELExitDate,
    cast(ELStatus as bool) as ELStatus,
    date(FirstEntryDateInUSSchool) as FirstEntryDateInUSSchool,
    ELASforTesting,
    CALPADSPrimaryLanguage,
    cast(PrimaryLanguageforTesting as string) as PrimaryLanguageforTesting,
    CEDSLanguageCode,
    cast(MilitaryStatus as bool) as MilitaryStatus,
    cast(FosterStatus as bool) as FosterStatus,
    cast(HomelessStatus as bool) as HomelessStatus,
    cast(EconomicDisadvantageStatus as bool) as EconomicDisadvantageStatus,
    cast(EconomicDisadvantageTesting as bool) as EconomicDisadvantageTesting,
    cast(ReportingEthnicity as string) as ReportingEthnicity,
    cast(ParentEducationLevel as string) as ParentEducationLevel,
    TestedStatus,
    cast(
        cast(right(cast(FinalTestedSchoolCode as string), 7) as int64) as string
    ) as FinalTestedSchoolCode,
    date(FinalTestCompletedDate) as FinalTestedCompletedDate,
    StudentExitCode,
    date(StudentExitDate) as StudentExitDate,
    date(StudentExitFileDate) as StudentExitFileDate,
    ConditionCode,
    cast(Attemptedness as string) as Attemptedness,
    cast(IncludeIndicator as string) as IncludeIndicator,
    case when cast(OverallScaleScore as string) = 'NS' then null else cast(OverallScaleScore as string) end as OverallScaleScore,
    case when cast(OverallPL as string) = 'NS' then null else cast(OverallPL as string) end as OverallPL,
    case when cast(OralLanguagePL as string) = 'NS' then null else cast(OralLanguagePL as string) end as OralLanguagePL,
    case when cast(WrittenLanguagePL as string) = 'NS' then null else cast(WrittenLanguagePL as string) end as WrittenLanguagePL,
    case when cast(ListeningPL as string) = 'NS' then null else cast(ListeningPL as string) end as ListeningPL,
    case when cast(SpeakingPL as string) = 'NS' then null else cast(SpeakingPL as string) end as SpeakingPL,
    case when cast(ReadingPL as string) = 'NS' then null else cast(ReadingPL as string) end as ReadingPL,
    case when cast(WritingPL as string) = 'NS' then null else cast(WritingPL as string) end as WritingPL,
    case when cast(AttemptednessMinus1 as string) = 'NS' then null else cast(AttemptednessMinus1 as string) end as AttemptednessMinus1,
    case when cast(GradeAssessedMinus1 as string) = 'NS' then null else cast(GradeAssessedMinus1 as string) end as GradeAssessedMinus1,
    case when cast(OverallScaleScoreMinus1 as string) = 'NS' then null else cast(OverallScaleScoreMinus1 as string) end as OverallScaleScoreMinus1,
    case when cast(OverallPLMinus1 as string) = 'NS' then null else cast(OverallPLMinus1 as string) end as OverallPLMinus1,
    case when cast(OralLanguagePLMinus1 as string) = 'NS' then null else cast(OralLanguagePLMinus1 as string) end as OralLanguagePLMinus1,
    case when cast(WrittenLanguagePLMinus1 as string) = 'NS' then null else cast(WrittenLanguagePLMinus1 as string) end as WrittenLanguagePLMinus1,
    case when cast(ListeningPLMinus1 as string) = 'NS' then null else cast(ListeningPLMinus1 as string) end as ListeningPLMinus1,
    case when cast(SpeakingPLMinus1 as string) = 'NS' then null else cast(SpeakingPLMinus1 as string) end as SpeakingPLMinus1,
    case when cast(ReadingPLMinus1 as string) = 'NS' then null else cast(ReadingPLMinus1 as string) end as ReadingPLMinus1,
    case when cast(WritingPLMinus1 as string) = 'NS' then null else cast(WritingPLMinus1 as string) end as WritingPLMinus1,
    case when cast(AttemptednessMinus2 as string) = 'NS' then null else cast(AttemptednessMinus2 as string) end as AttemptednessMinus2,
    case when cast(GradeAssessedMinus2 as string) = 'NS' then null else cast(GradeAssessedMinus2 as string) end as GradeAssessedMinus2,
    case when cast(OverallScaleScoreMinus2 as string) = 'NS' then null else cast(OverallScaleScoreMinus2 as string) end as OverallScaleScoreMinus2,
    case when cast(OverallPLMinus2 as string) = 'NS' then null else cast(OverallPLMinus2 as string) end as OverallPLMinus2,
    case when cast(OralLanguagePLMinus2 as string) = 'NS' then null else cast(OralLanguagePLMinus2 as string) end as OralLanguagePLMinus2,
    case when cast(WrittenLanguagePLMinus2 as string) = 'NS' then null else cast(WrittenLanguagePLMinus2 as string) end as WrittenLanguagePLMinus2,
    case when cast(ListeningPLMinus2 as string) = 'NS' then null else cast(ListeningPLMinus2 as string) end as ListeningPLMinus2,
    case when cast(SpeakingPLMinus2 as string) = 'NS' then null else cast(SpeakingPLMinus2 as string) end as SpeakingPLMinus2,
    case when cast(ReadingPLMinus2 as string) = 'NS' then null else cast(ReadingPLMinus2 as string) end as ReadingPLMinus2,
    case when cast(WritingPLMinus2 as string) = 'NS' then null else cast(WritingPLMinus2 as string) end as WritingPLMinus2,
    case when cast(AttemptednessMinus3 as string) = 'NS' then null else cast(AttemptednessMinus3 as string) end as AttemptednessMinus3,
    case when cast(GradeAssessedMinus3 as string) = 'NS' then null else cast(GradeAssessedMinus3 as string) end as GradeAssessedMinus3,
    case when cast(OverallScaleScoreMinus3 as string) = 'NS' then null else cast(OverallScaleScoreMinus3 as string) end as OverallScaleScoreMinus3,
    case when cast(OverallPLMinus3 as string) = 'NS' then null else cast(OverallPLMinus3 as string) end as OverallPLMinus3,
    case when cast(OralLanguagePLMinus3 as string) = 'NS' then null else cast(OralLanguagePLMinus3 as string) end as OralLanguagePLMinus3,
    case when cast(WrittenLanguagePLMinus3 as string) = 'NS' then null else cast(WrittenLanguagePLMinus3 as string) end as WrittenLanguagePLMinus3,
    case when cast(ListeningPLMinus3 as string) = 'NS' then null else cast(ListeningPLMinus3 as string) end as ListeningPLMinus3,
    case when cast(SpeakingPLMinus3 as string) = 'NS' then null else cast(SpeakingPLMinus3 as string) end as SpeakingPLMinus3,
    case when cast(ReadingPLMinus3 as string) = 'NS' then null else cast(ReadingPLMinus3 as string) end as ReadingPLMinus3,
    case when cast(WritingPLMinus3 as string) = 'NS' then null else cast(WritingPLMinus3 as string) end as WritingPLMinus3
from {{ source('RawData', 'TomsElpacEnrolledInspire')}}