select
    format("%02d", CountyCode) as CountyCode,
    format("%05d", DistrictCode) as DistrictCode,
    format("%07d", SchoolCode) as SchoolCode,
    format("%02d", RecordType) as RecordType,
    cast(CharterNumber as string) as CharterNumber,
    cast(TestYear as int64) as TestYear,
    cast(StudentGroupID as string) as StudentGroupId,
    cast(case when AssessmentType = 2 then 21 end as string) as AssessmentType,
    cast(nullif(TotalEnrolled, '*') as int64) as TotalEnrolled,
    cast(case when TotalTested not in ('*','') then TotalTested end as int64) as TotalTested,
    cast(null as int64) as TotalTestedWithScores,
    case when Grade = 'KN' then 0 else cast(Grade as int64) end GradeLevel,
    cast(case when OverallMeanSclScr not in ('*','') then OverallMeanSclScr end as float64) as OverallMeanSclScr,
    round(cast(case when OverallPerfLvl1Pcnt not in ('*','') then OverallPerfLvl1Pcnt end as float64) / 100, 4) as OverallPerfLvl1Pcnt,
    cast(case when OverallPerfLvl1Count not in ('*','') then OverallPerfLvl1Count end as int64) as OverallPerfLvl1Count,
    round(cast(case when OverallPerfLvl2Pcnt not in ('*','') then OverallPerfLvl2Pcnt end as float64) / 100, 4) as OverallPerfLvl2Pcnt,
    cast(case when OverallPerfLvl2Count not in ('*','') then OverallPerfLvl2Count end as int64) as OverallPerfLvl2Count,
    round(cast(case when OverallPerfLvl3Pcnt not in ('*','') then OverallPerfLvl3Pcnt end as float64) / 100, 4) as OverallPerfLvl3Pcnt,
    cast(case when OverallPerfLvl3Count not in ('*','') then OverallPerfLvl3Count end as int64) as OverallPerfLvl3Count,
    round(cast(case when OverallPerfLvl4Pcnt not in ('*','') then OverallPerfLvl4Pcnt end as float64) / 100, 4) as OverallPerfLvl4Pcnt,
    cast(case when OverallPerfLvl4Count not in ('*','') then OverallPerfLvl4Count end as int64) as OverallPerfLvl4Count,
    cast(case when OverallTotal not in ('*','') then OverallTotal end as int64) as OverallTotal,
    cast(case when OralLangMeanSclScr not in ('*','') then OralLangMeanSclScr end as float64) as OralLangMeanSclScr,
    round(cast(case when OralLangPerfLvl1Pcnt not in ('*','') then OralLangPerfLvl1Pcnt end as float64) / 100, 4) as OralLangPerfLvl1Pcnt,
    cast(case when OralLangPerfLvl1Count not in ('*','') then OralLangPerfLvl1Count end as int64) as OralLangPerfLvl1Count,
    round(cast(case when OralLangPerfLvl2Pcnt not in ('*','') then OralLangPerfLvl2Pcnt end as float64) / 100, 4) as OralLangPerfLvl2Pcnt,
    cast(case when OralLangPerfLvl2Count not in ('*','') then OralLangPerfLvl2Count end as int64) as OralLangPerfLvl2Count,
    round(cast(case when OralLangPerfLvl3Pcnt not in ('*','') then OralLangPerfLvl3Pcnt end as float64) / 100, 4) as OralLangPerfLvl3Pcnt,
    cast(case when OralLangPerfLvl3Count not in ('*','') then OralLangPerfLvl3Count end as int64) as OralLangPerfLvl3Count,
    round(cast(case when OralLangPerfLvl4Pcnt not in ('*','') then OralLangPerfLvl4Pcnt end as float64) / 100, 4) as OralLangPerfLvl4Pcnt,
    cast(case when OralLangPerfLvl4Count not in ('*','') then OralLangPerfLvl4Count end as int64) as OralLangPerfLvl4Count,
    cast(case when OralLangTotal not in ('*','') then OralLangTotal end as int64) as OralLangTotal,
    cast(case when WritLangMeanSclScr not in ('*','') then WritLangMeanSclScr end as float64) as WritLangMeanSclScr,
    round(cast(case when WritLangPerfLvl1Pcnt not in ('*','') then WritLangPerfLvl1Pcnt end as float64) / 100, 4) as WritLangPerfLvl1Pcnt,
    cast(case when WritLangPerfLvl1Count not in ('*','') then WritLangPerfLvl1Count end as int64) as WritLangPerfLvl1Count,
    round(cast(case when WritLangPerfLvl2Pcnt not in ('*','') then WritLangPerfLvl2Pcnt end as float64) / 100, 4) as WritLangPerfLvl2Pcnt,
    cast(case when WritLangPerfLvl2Count not in ('*','') then WritLangPerfLvl2Count end as int64) as WritLangPerfLvl2Count,
    round(cast(case when WritLangPerfLvl3Pcnt not in ('*','') then WritLangPerfLvl3Pcnt end as float64) / 100, 4) as WritLangPerfLvl3Pcnt,
    cast(case when WritLangPerfLvl3Count not in ('*','') then WritLangPerfLvl3Count end as int64) as WritLangPerfLvl3Count,
    round(cast(case when WritLangPerfLvl4Pcnt not in ('*','') then WritLangPerfLvl4Pcnt end as float64) / 100, 4) as WritLangPerfLvl4Pcnt,
    cast(case when WritLangPerfLvl4Count not in ('*','') then WritLangPerfLvl4Count end as int64) as WritLangPerfLvl4Count,
    cast(case when WritLangTotal not in ('*','') then WritLangTotal end as int64) as WritLangTotal,
    round(cast(case when ListeningDomainBeginPcnt not in ('*','') then ListeningDomainBeginPcnt end as float64) / 100, 4) as ListeningDomainBeginPcnt,
    cast(case when ListeningDomainBeginCount not in ('*','') then ListeningDomainBeginCount end as int64) as ListeningDomainBeginCount,
    round(cast(case when ListeningDomainModeratePcnt not in ('*','') then ListeningDomainModeratePcnt end as float64) / 100, 4) as ListeningDomainModeratePcnt,
    cast(case when ListeningDomainModerateCount not in ('*','') then ListeningDomainModerateCount end as int64) as ListeningDomainModerateCount,
    round(cast(case when ListeningDomainDevelopedPcnt not in ('*','') then ListeningDomainDevelopedPcnt end as float64) / 100, 4) as ListeningDomainDevelopedPcnt,
    cast(case when ListeningDomainDevelopedCount not in ('*','') then ListeningDomainDevelopedCount end as int64) as ListeningDomainDevelopedCount,
    cast(case when ListeningDomainTotal not in ('*','') then ListeningDomainTotal end as int64) as ListeningDomainTotal,
    round(cast(case when SpeakingDomainBeginPcnt not in ('*','') then SpeakingDomainBeginPcnt end as float64) / 100, 4) as SpeakingDomainBeginPcnt,
    cast(case when SpeakingDomainBeginCount not in ('*','') then SpeakingDomainBeginCount end as int64) as SpeakingDomainBeginCount,
    round(cast(case when SpeakingDomainModeratePcnt not in ('*','') then SpeakingDomainModeratePcnt end as float64) / 100, 4) as SpeakingDomainModeratePcnt,
    cast(case when SpeakingDomainModerateCount not in ('*','') then SpeakingDomainModerateCount end as int64) as SpeakingDomainModerateCount,
    round(cast(case when SpeakingDomainDevelopedPcnt not in ('*','') then SpeakingDomainDevelopedPcnt end as float64) / 100, 4) as SpeakingDomainDevelopedPcnt,
    cast(case when SpeakingDomainDevelopedCount not in ('*','') then SpeakingDomainDevelopedCount end as int64) as SpeakingDomainDevelopedCount,
    cast(case when SpeakingDomainTotal not in ('*','') then SpeakingDomainTotal end as int64) as SpeakingDomainTotal,
    round(cast(case when ReadingDomainBeginPcnt not in ('*','') then ReadingDomainBeginPcnt end as float64) / 100, 4) as ReadingDomainBeginPcnt,
    cast(case when ReadingDomainBeginCount not in ('*','') then ReadingDomainBeginCount end as int64) as ReadingDomainBeginCount,
    round(cast(case when ReadingDomainModeratePcnt not in ('*','') then ReadingDomainModeratePcnt end as float64) / 100, 4) as ReadingDomainModeratePcnt,
    cast(case when ReadingDomainModerateCount not in ('*','') then ReadingDomainModerateCount end as int64) as ReadingDomainModerateCount,
    round(cast(case when ReadingDomainDevelopedPcnt not in ('*','') then ReadingDomainDevelopedPcnt end as float64) / 100, 4) as ReadingDomainDevelopedPcnt,
    cast(case when ReadingDomainDevelopedCount not in ('*','') then ReadingDomainDevelopedCount end as int64) as ReadingDomainDevelopedCount,
    cast(case when ReadingDomainTotal not in ('*','') then ReadingDomainTotal end as int64) as ReadingDomainTotal,
    round(cast(case when WritingDomainBeginPcnt not in ('*','') then WritingDomainBeginPcnt end as float64) / 100, 4) as WritingDomainBeginPcnt,
    cast(case when WritingDomainBeginCount not in ('*','') then WritingDomainBeginCount end as int64) as WritingDomainBeginCount,
    round(cast(case when WritingDomainModeratePcnt not in ('*','') then WritingDomainModeratePcnt end as float64) / 100, 4) as WritingDomainModeratePcnt,
    cast(case when WritingDomainModerateCount not in ('*','') then WritingDomainModerateCount end as int64) as WritingDomainModerateCount,
    round(cast(case when WritingDomainDevelopedPcnt not in ('*','') then WritingDomainDevelopedPcnt end as float64) / 100, 4) as WritingDomainDevelopedPcnt,
    cast(case when WritingDomainDevelopedCount not in ('*','') then WritingDomainDevelopedCount end as int64) as WritingDomainDevelopedCount,
    cast(case when WritingDomainTotal not in ('*','') then WritingDomainTotal end as int64) as WritingDomainTotal,
from {{ source('RawData', 'Elpac2018')}}
