select
    format('%02d', County_Code) as CountyCode,
    format('%05d', District_Code) as DistrictCode,
    format('%07d', School_Code) as SchoolCode,
    Filler,
    cast(Test_Year as int64) as TestYear,
    cast(Demographic_ID as string) as DemographicId,
    Test_Type as TestType,
    cast(nullif(Total_Number_Tested_At_Entity_Level_and_Demographic, '*') as int64) as TotalTestedAtReportingLevel,
    cast(nullif(Total_Number_Tested_at_this_Demographic_with_Valid_Scores, '*') as int64) as TotalTestedWithScoresAtReportingLevel,
    cast(Grade as int64) as GradeLevel,
    cast(Test_ID as string) as TestId,
    cast(nullif(CAST_Reported_Enrollment, '*') as int64) as StudentsEnrolled,
    cast(nullif(Total_Number_of_Students_Tested, '*') as int64) as StudentsTested,
    cast(case when Mean_Scale_Score not in ('*', '', '0.0') then Mean_Scale_Score end as float64) as MeanScaleScore,
    cast(nullif(Percentage_Standard_Exceeded, '*') as float64) as PctStandardExceeded,
    cast(nullif(Percentage_Standard_Met, '*') as float64) as PctStandardMet,
    cast(nullif(Percentage_Standard_Met_and_Above, '*') as float64) as PctStandardMetandAbove,
    cast(nullif(Percentage_Standard_Nearly_Met, '*') as float64) as PctStandardNearlyMet,
    cast(nullif(Percentage_Standard_Not_Met, '*') as float64) as PctStandardNotMet,
    cast(nullif(Total_Number_of_Students_with_Valid_Scores, '*') as int64) as StudentsWithScores,
    cast(nullif(Life_Sciences_Domain_Percent_Below_Standard, '*') as float64) as LifeSciencesDomainPercentBelowStandard,
    cast(nullif(Life_Sciences_Domain_Percent_Near_Standard, '*') as float64) as LifeSciencesDomainPercentNearStandard,
    cast(nullif(Life_Sciences_Domain_Percent_Above_Standard, '*') as float64) as LifeSciencesDomainPercentAboveStandard,
    cast(nullif(Physical_Sciences_Domain_Percent_Below_Standard, '*') as float64) as PhysicalSciencesDomainPercentBelowStandard,
    cast(nullif(Physical_Sciences_Domain_Percent_Near_Standard, '*') as float64) as PhysicalSciencesDomainPercentNearStandard,
    cast(nullif(Physical_Sciences_Domain_Percent_Above_Standard, '*') as float64) as PhysicalSciencesDomainPercentAboveStandard,
    cast(nullif(Earth_and_Space_Sciences_Domain_Percent_Below_Standard, '*') as float64) as EarthAndSpaceSciencesDomainPercentBelowStandard,
    cast(nullif(Earth_and_Space_Sciences_Domain_Percent_Near_Standard, '*') as float64) as EarthAndSpaceSciencesDomainPercentNearStandard,
    cast(nullif(Earth_and_Space_Sciences_Domain_Percent_Above_Standard, '*') as float64) as EarthAndSpaceSciencesDomainPercentAboveStandard,
    cast(null as string) as TypeId
from {{ source('RawData', 'Cast2019') }}
