select
    RecordType,
    SSID,
    StudentLastName,
    StudentFirstName,
    StudentMiddleName,
    date(DateofBirth) as DateofBirth,
    Gender,
    cast(cast(GradeAssessed as int64) as string) as GradeAssessed,
    cast(cast(right(CALPADSSchoolCode, 7) as int64) as string) as CALPADSSchoolCode,
    CALPADSSchoolName,
    coalesce(Section504Status = 'Yes', false) as Section504Status,
    coalesce(CALPADSIDEAIndicator = 'Yes', false) as CALPADSIDEAIndicator,
    coalesce(IDEAIndicatorForTesting = 'Yes', false) as IDEAIndicatorForTesting,
    coalesce(MigrantStatus = 'Yes', false) as MigrantStatus,
    coalesce(ELStatus = 'Yes', false) as ELStatus,
    date(ELEntryDate) as ELEntryDate,
    date(RFEPDate) as RFEPDate,
    date(FirstEntryDateInUSSchool) as FirstEntryDateInUSSchool,
    date(EnrollmentEffectiveDate) as EnrollmentEffectiveDate,
    ELAS,
    CEDSLanguageCode,
    CALPADSPrimaryLanguage,
    coalesce(MilitaryStatus = 'Yes', false) as MilitaryStatus,
    coalesce(FosterStatus = 'Yes', false) as FosterStatus,
    coalesce(EconomicDisadvantageStatus = 'Yes', false) as EconomicDisadvantageStatus,
    coalesce(EconomicDisadvantageTesting = 'Yes', false) as EconomicDisadvantageTesting,
    coalesce(CALPADSNPSSchoolFlag = 'Y', false) as CALPADSNPSSchoolFlag,
    coalesce(HispanicorLatino = 'Yes', false) as HispanicorLatino,
    coalesce(AmericanIndianorAlaskaNative = 'Yes', false) as AmericanIndianorAlaskaNative,
    coalesce(Asian = 'Yes', false) as Asian,
    coalesce(HawaiianOrOtherPacificIslander = 'Yes', false) as HawaiianOrOtherPacificIslander,
    coalesce(Filipino = 'Yes', false) as Filipino,
    coalesce(BlackorAfricanAmerican = 'Yes', false) as BlackorAfricanAmerican,
    coalesce(White = 'Yes', false) as White,
    coalesce(TwoorMoreRaces = 'Yes', false) as TwoorMoreRaces,
    ReportingEthnicity,
    cast(cast(right(FinalTestedSchoolCode, 7) as int64) as string) as FinalTestedSchoolCode,
    StudentExitCode,
    date(StudentExitWithdrawalDate) as StudentExitWithdrawalDate,
    date(StudentRemovedCALPADSFileDate) as StudentRemovedCALPADSFileDate,
    ConditionCode,
    Attemptedness,
    ScoreStatus,
    case
        when IncludeIndicator = 'true' then 'Y'
        when IncludeIndicator = 'false' then 'N'
        else IncludeIndicator
    end as IncludeIndicator,
    LexileorQuantileMeasure,
    GrowthScore,
    cast(ScaleScore as int64) as ScaleScore,
    cast(AchievementLevels as int64) as AchievementLevels,
    cast(cast(GradeAssessedMinus1 as int64) as string) as GradeAssessedMinus1,
    cast(ScaleScoreMinus1 as int64) as ScaleScoreMinus1,
    cast(AchievementLevelMinus1 as int64) as AchievementLevelMinus1,
    cast(cast(GradeAssessedMinus2 as int64) as string) as GradeAssessedMinus2,
    cast(ScaleScoreMinus2 as int64) as ScaleScoreMinus2,
    cast(AchievementLevelMinus2 as int64) as AchievementLevelMinus2,
    cast(cast(GradeAssessedMinus3 as int64) as string) as GradeAssessedMinus3,
    cast(ScaleScoreMinus3 as int64) as ScaleScoreMinus3,
    cast(AchievementLevelMinus3 as int64) as AchievementLevelMinus3
from {{ source('RawData', 'TomsCaasppTested2023Inspire')}}