select
    case subject
        when 'ELA' then '14'
        when 'Math' then '19'
    end as AceAssessmentId,
    concat('ANet ', Subject) as AceAssessmentName,
    case when school_id = 100966 then '0125617' end as StateSchoolCode,
    cast(school_year as int64) as SchoolYear,
    cast(school_id as int64) as SchoolId,
    cast(school_name as string) as SchoolName,
    cast(school_system_name as string) as SchoolSystemName,
    cast(school_cluster as string) as SchoolCluster,
    cast(student_id as int64) as StudentId,
    cast(sas_id as int64) as SasId,
    cast(sis_id as int64) as SisId,
    cast(student_first_name as string) as StudentFirstName,
    cast(student_middle_name as string) as StudentMiddleName,
    cast(student_last_name as string) as StudentLastName,
    cast(enrollment_grade as string) as EnrollmentGrade,
    cast(course as string) as Course,
    date(birth_date) as BirthDate,
    cast(gender as string) as Gender,
    cast(race as string) as Race,
    cast(frl_status as int64) as FrlStatus,
    cast(lep_status as int64) as LepStatus,
    cast(sped_status as int64) as SpedStatus,
    cast(previous_state_level as string) as PreviousStateLevel,
    cast(previous_state_score as int64) as PreviousStateScore,
    cast(period as string) as Period,
    cast(teacher_first_name as string) as TeacherFirstName,
    cast(teacher_last_name as string) as TeacherLastName,
    cast(cycle as int64) as Cycle,
    cast(subject as string) as Subject,
    cast(sas_name as string) as SasName,
    cast(assessment_id as string) as AssessmentId,
    cast(assessment_name as string) as AssessmentName,
    cast(super_genre as string) as SuperGenre,
    cast(genre as string) as Genre,
    cast(passage_id as string) as PassageId,
    cast(passage_title as string) as PassageTitle,
    cast(domain as string) as Domain,
    cast(cluster_designation as string) as ClusterDesignation,
    cast(cluster_code as string) as ClusterCode,
    cast(cc_standard_code as string) as CcStandardCode,
    cast(item_id as string) as ItemId,
    cast(question_id as string) as QuestionId,
    cast(item_type as string) as ItemType,
    cast(question_position as string) as QuestionPosition,
    cast(response as string) as Response,
    cast(correct_Answer_Value as string) as CorrectAnswerValue,
    cast(points_received as int64) as PointsReceived,
    cast(points_possible as int64) as PointsPossible,
    case when item_type = 'Open Response' then 'Teacher' else 'Machine' end as ScoredBy
from {{ source('RawData', 'Anet2022MachineScored') }}
