SELECT
  SchoolId,
  CAST(StateCdsCode AS STRING) AS StateCdsCode, 
  CAST(StateCountyCode AS STRING) AS StateCountyCode,
  CAST(StateDistrictCode AS STRING) AS StateDistrictCode,
  FORMAT("%07d", StateSchoolCode) AS StateSchoolCode,
  SchoolNameFull,
  SchoolNameMid,
  SchoolNameShort,
  SchoolType,
  MinGrade,
  MaxGrade,
  Grade5,
  Grade6,
  Grade7,
  Grade8,
  Grade9,
  Grade10,
  Grade11,
  Grade12,
  CAST(YearOpened AS INT64) AS YearOpened,
  PreviousRenewalYears,
  DATE(CurrentCharterTermStartDate) AS CurrentCharterTermStartDate,
  DATE(CurrentCharterTermEndDate) AS CurrentCharterTermEndDate
FROM {{ source('GoogleSheetData', 'Schools')}}