SELECT
  CAST(SchoolId AS STRING) AS SchoolId,
  FORMAT("%014d", StateCdsCode) AS StateCdsCode,
  FORMAT("%02d", StateCountyCode) AS StateCountyCode,
  FORMAT("%02d", StateDistrictCode) AS StateDistrictCode,
  FORMAT("%07d", StateSchoolCode) AS StateSchoolCode,
  SchoolNameFull,
  SchoolNameMid,
  SchoolNameShort,
  SchoolType,
  MinGrade,
  MaxGrade,
  CONCAT(CAST(MinGrade AS STRING),'-',CAST(MaxGrade AS STRING)) AS GradesServed,
  Grade5,
  Grade6,
  Grade7,
  Grade8,
  Grade9,
  Grade10,
  Grade11,
  Grade12,
  CAST(YearOpened AS INT64) AS YearOpened,
  PreviousRenewalYears,
  DATE(CurrentCharterTermStartDate) AS CurrentCharterTermStartDate,
  DATE(CurrentCharterTermEndDate) AS CurrentCharterTermEndDate
FROM {{ source('GoogleSheetData', 'Schools')}}